# Generated by Django 4.1.5 on 2023-01-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CROP', '0001_initial'),
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUnit',
            fields=[
                ('suid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='SUID')),
                ('unit', models.CharField(max_length=32, unique=True, verbose_name='Unit')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVariety',
            fields=[
                ('svid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='SVID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Variety Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('stid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='STID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('level', models.SmallIntegerField(choices=[(1, 'top'), (2, 'middle'), (3, 'base')], verbose_name='Level')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_st', to='SITE.sitetype', verbose_name='Parent Site Type')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('sid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='SID')),
                ('name', models.CharField(max_length=256, verbose_name='Site Name')),
                ('owner_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Owner Name')),
                ('crop_year', models.IntegerField(blank=True, null=True, verbose_name='Crop Year')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='Size')),
                ('gps', models.CharField(blank=True, max_length=128, null=True, verbose_name='GPS')),
                ('gps_system', models.CharField(blank=True, max_length=64, null=True, verbose_name='GPS System')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_crop', to='CROP.crop', verbose_name='Crop')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_site', to='SITE.site', verbose_name='Parent Site')),
                ('size_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_unit', to='SITE.siteunit', verbose_name='Size Unit')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_type', to='SITE.sitetype', verbose_name='Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_user', to='USER.user', verbose_name='User')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_variety', to='SITE.sitevariety', verbose_name='Variety')),
            ],
        ),
    ]
