# Generated by Django 4.1.5 on 2023-01-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITE', '0002_rename_site_name_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_st', to='SITE.sitetype', verbose_name='Parent Site Type'),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'top'), (2, 'middle'), (3, 'base')], verbose_name='Level'),
        ),
    ]
