# Generated by Django 4.1.5 on 2023-01-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER', '0008_alter_userrelation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CID')),
                ('crop_name', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_user', to='USER.user', verbose_name='User')),
            ],
        ),
    ]
