# Generated by Django 4.1.5 on 2023-01-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CROP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('ccid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CCID')),
                ('category_name', models.CharField(max_length=128, verbose_name='Category Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('cgsid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CGSID')),
                ('stage_name', models.CharField(max_length=128, verbose_name='Stage Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='CropLifecycle',
            fields=[
                ('clcid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='CLCID')),
                ('lifecycle_name', models.CharField(max_length=128, verbose_name='Lifecycle Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='crop',
            name='variety_list',
            field=models.CharField(default=1, max_length=256, verbose_name='Variety List'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.SmallIntegerField(choices=[(1, 'Apple'), (2, 'Berry'), (3, 'Cherry'), (4, 'Grape'), (5, 'Pear'), (6, 'Stone Fruit'), (7, 'Golf'), (8, 'Ground'), (9, 'Lawn'), (10, 'Sod')], verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_category', to='CROP.cropcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_growth_stage', to='CROP.cropgrowthstage', verbose_name='Grow Stage'),
        ),
        migrations.AddField(
            model_name='crop',
            name='lifecycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_lifecycle', to='CROP.croplifecycle', verbose_name='Lifecycle'),
        ),
    ]
