# Generated by Django 4.1.5 on 2023-01-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CROP', '0002_cropcategory_cropgrowthstage_croplifecycle_crop_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cropcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cropgrowthstage',
            old_name='stage_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='croplifecycle',
            old_name='lifecycle_name',
            new_name='name',
        ),
    ]
