# Generated by Django 4.1.5 on 2023-01-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER', '0013_rename_type_name_userrelationtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('optid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='OPTID')),
                ('name', models.CharField(max_length=128, verbose_name='Type Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='OperationUnit',
            fields=[
                ('opuid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='OPUID')),
                ('unit', models.CharField(max_length=32, verbose_name='Unit')),
                ('usage', models.SmallIntegerField(choices=[(1, 'Area'), (2, 'Liquid')], verbose_name='Usage')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('opid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='OPID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Operation Datetime')),
                ('multiple_site', models.BooleanField(default=False, verbose_name='Multiple Site')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_type', to='OPERATION.operationtype', verbose_name='Operation Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_user', to='USER.user', verbose_name='User')),
            ],
        ),
    ]
