# Generated by Django 4.1.5 on 2023-01-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='UID')),
                ('Username', models.CharField(max_length=64, unique=True, verbose_name='User Name')),
                ('Password', models.CharField(max_length=32, verbose_name='Password')),
                ('Name', models.CharField(max_length=64, verbose_name='Actual Name')),
                ('BusinessName', models.CharField(max_length=256, verbose_name='Business Name')),
                ('RegistrationNo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Registration No.')),
                ('RegExpireDate', models.DateField(blank=True, null=True, verbose_name='Registration Expire Date')),
                ('Address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('City', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('County', models.CharField(blank=True, max_length=64, null=True, verbose_name='County')),
                ('State', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('Zipcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Zip Code')),
                ('Country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('Phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('Cell', models.CharField(blank=True, max_length=16, null=True, verbose_name='Cell Number')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('SelfActivated', models.BooleanField(verbose_name='Self Activated Status')),
                ('Valid', models.BooleanField(default=False, verbose_name='Valid Status')),
                ('AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraddedby', to='USER.user', verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationType',
            fields=[
                ('URTID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URTID')),
                ('TypeName', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('Note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('Valid', models.BooleanField(default=True, verbose_name='Valid Status')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('UTID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='UTID')),
                ('TypeName', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('InfoDataTable', models.CharField(blank=True, max_length=256, null=True, verbose_name='Info Data Table')),
                ('Valid', models.BooleanField(default=True, verbose_name='Valid Status')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('URID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URID')),
                ('Valid', models.BooleanField(default=False, verbose_name='Valid Status')),
                ('AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationaddedby', to='USER.user', verbose_name='Added By')),
                ('Provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='USER.user', verbose_name='Provider')),
                ('RelationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationtype', to='USER.userrelationtype', verbose_name='Relation Type')),
                ('Requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to='USER.user', verbose_name='Requester')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertype', to='USER.usertype', verbose_name='User Type'),
        ),
    ]
