# Generated by Django 4.1.5 on 2023-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Time'),
        ),
    ]
