# Generated by Django 4.1.5 on 2023-01-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UID',
            new_name='UUID',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='UTID',
            new_name='UUID',
        ),
    ]
