# Generated by Django 4.1.5 on 2023-01-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_rename_uid_user_uuid_rename_utid_usertype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='InfoDataTable',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Info Data Table'),
        ),
    ]
