# Generated by Django 4.1.5 on 2023-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_rename_address_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='self_activated',
            field=models.BooleanField(default=False, verbose_name='Self Activated'),
        ),
    ]
