# Generated by Django 4.1.5 on 2023-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_alter_user_self_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='InfoDataTable',
            new_name='info_data_table',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='TypeName',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='UTID',
            new_name='utid',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='Valid',
        ),
        migrations.AddField(
            model_name='usertype',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
