# Generated by Django 4.1.5 on 2023-01-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_rename_uuid_user_uid_rename_uuid_usertype_utid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='TypeName',
            field=models.CharField(max_length=128, verbose_name='Type Name'),
        ),
    ]
