# Generated by Django 4.1.5 on 2023-01-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_rename_infodatatable_usertype_info_data_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelation',
            old_name='Provider',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='RelationType',
            new_name='relation_type',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='Requester',
            new_name='requester',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='URID',
            new_name='urid',
        ),
        migrations.RenameField(
            model_name='userrelationtype',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='userrelationtype',
            old_name='TypeName',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='userrelationtype',
            old_name='URTID',
            new_name='urtid',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='AddedBy',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='Valid',
        ),
        migrations.RemoveField(
            model_name='userrelationtype',
            name='Valid',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_added_by', to='USER.user', verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='userrelationtype',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='userrelationtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
