# Generated by Django 4.1.5 on 2023-01-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_alter_usertype_typename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='user',
            name='Valid',
            field=models.BooleanField(default=True, verbose_name='Valid Status'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='Valid',
            field=models.BooleanField(default=True, verbose_name='Valid Status'),
        ),
    ]
