# Generated by Django 4.1.5 on 2023-01-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_rename_provider_userrelation_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
