# Generated by Django 4.1.5 on 2023-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
