# Generated by Django 4.1.5 on 2023-01-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_alter_user_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationType',
            fields=[
                ('URTID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URTID')),
                ('TypeName', models.CharField(max_length=128, unique=True, verbose_name='Type Name')),
                ('Note', models.TextField(blank=True, null=True, verbose_name='Info Data Table')),
                ('Valid', models.BooleanField(default=True, verbose_name='Valid Status')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='AddedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraddedby', to='USER.user', verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertype', to='USER.usertype', verbose_name='User Type'),
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('URID', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='URID')),
                ('Valid', models.BooleanField(default=False, verbose_name='Valid Status')),
                ('AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationaddedby', to='USER.user', verbose_name='Added By')),
                ('Provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='USER.user', verbose_name='Provider')),
                ('RelationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationtype', to='USER.userrelationtype', verbose_name='Relation Type')),
                ('Requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to='USER.user', verbose_name='Requester')),
            ],
        ),
    ]
