# Generated by Django 4.1.5 on 2023-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_userrelationtype_alter_user_addedby_alter_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelationtype',
            name='Note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
