# Generated by Django 4.1.5 on 2023-01-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_alter_user_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='Username'),
        ),
    ]
