# Generated by Django 4.1.5 on 2023-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Actual Name'),
        ),
    ]
