# Generated by Django 4.1.5 on 2023-01-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0011_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_user', to='USER.user', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_user', to='USER.user', verbose_name='Requester'),
        ),
    ]
