# Generated by Django 4.1.5 on 2023-01-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0012_alter_userrelation_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelationtype',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='type_name',
            new_name='name',
        ),
    ]
