# Generated by Django 4.1.5 on 2023-01-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalType',
            fields=[
                ('chemtid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ChemTID')),
                ('name', models.CharField(max_length=128, verbose_name='Type Name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalUnit',
            fields=[
                ('chemuid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ChemUID')),
                ('unit', models.CharField(max_length=128, verbose_name='Unit')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('chemid', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='ChemID')),
                ('trade_name', models.CharField(max_length=128, verbose_name='Trade Name')),
                ('epa_reg_no', models.CharField(max_length=64, verbose_name='EPA Registration No.')),
                ('formulation', models.CharField(max_length=128, verbose_name='Formulation')),
                ('active_ingredient', models.CharField(max_length=128, verbose_name='Active Ingredient')),
                ('percent_ai', models.FloatField(verbose_name='Active Ingredient Percent')),
                ('rei', models.FloatField(verbose_name='REI')),
                ('phi', models.IntegerField(verbose_name='PHI')),
                ('labeled_crops', models.CharField(blank=True, max_length=256, null=True, verbose_name='Labeled Crops')),
                ('restricted_use', models.BooleanField(default=False, verbose_name='Is Active')),
                ('label_image', models.CharField(blank=True, max_length=128, null=True, verbose_name='Labeled Image')),
                ('imported_from', models.CharField(blank=True, max_length=32, null=True, verbose_name='Imported From')),
                ('validated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Validated By')),
                ('entered_year', models.IntegerField(blank=True, null=True, verbose_name='Entered Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Create Time')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_type', to='CHEMICAL.chemicaltype', verbose_name='Chemical Type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_unit', to='CHEMICAL.chemicalunit', verbose_name='Application Unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_user', to='USER.user', verbose_name='User')),
            ],
        ),
    ]
